export const tableData = [
    { "FirstName": "Sree Priyanka", "LastName": "Onteru", "DOB": "21 may", "College": "KLU", "Citizenship": "India", "Place": "AP", "City": "Guntur", "MotherName": "Suneetha", "FatherName": "OSR", "Siblings": "No", "Zipcode": "522213", "Linkedin": "https://abc.com", "Contact": "1234567", "Gmail": "abcsdfhjgjkfgfhgjkhjlkjhgfsdgfhgjkhlhkfhgjkhjhjghgfhgjkhjl;khgjkhldfghjgkhjlk;l';hhhhh@gmail.com", "Profession": "Software", "Hobbies": "Sleep", "ZodiacSign": "Cancer", "FavoriteGame": "Chess", "FavoriteFood": "Chicken", "Religion": "Muslim" },
    { "FirstName": "Sree Priyanka", "LastName": "Onteru", "DOB": "26 may", "College": "KLU", "Citizenship": "India", "Place": "AP", "City": "Guntur", "MotherName": "Suneetha", "FatherName": "OSR", "Siblings": "No", "Zipcode": "522213", "Linkedin": "https://abc.com", "Contact": "1234567", "Gmail": "abc@gmail.com", "Profession": "Software", "Hobbies": "Sleep", "ZodiacSign": "Cancer", "FavoriteGame": "Chess", "FavoriteFood": "Chicken", "Religion": "Muslim" },
    { "FirstName": "Sree Priyanka", "LastName": "Onteru", "DOB": "21 may", "College": "KLU", "Citizenship": "India", "Place": "AP", "City": "Guntur", "MotherName": "Suneetha", "FatherName": "OSR", "Siblings": "No", "Zipcode": "522213", "Linkedin": "https://abc.com", "Contact": "1234567", "Gmail": "abc@gmail.com", "Profession": "Software", "Hobbies": "Sleep", "ZodiacSign": "Cancer", "FavoriteGame": "Chess", "FavoriteFood": "Chicken", "Religion": "Muslim" },
    { "FirstName": "Sree Priyanka", "LastName": "Onteru", "DOB": "27 may", "College": "KLU", "Citizenship": "India", "Place": "AP", "City": "Guntur", "MotherName": "Suneetha", "FatherName": "OSR", "Siblings": "No", "Zipcode": "522213", "Linkedin": "https://abc.com", "Contact": "1234567", "Gmail": "abc@gmail.com", "Profession": "Software", "Hobbies": "Sleep", "ZodiacSign": "Cancer", "FavoriteGame": "Chess", "FavoriteFood": "Chicken", "Religion": "Muslim" },
    { "FirstName": "Sree Priyanka", "LastName": "Onteru", "DOB": "21 may", "College": "KLU", "Citizenship": "India", "Place": "AP", "City": "Guntur", "MotherName": "Suneetha", "FatherName": "OSR", "Siblings": "No", "Zipcode": "522213", "Linkedin": "https://abc.com", "Contact": "1234567", "Gmail": "abc@gmail.com", "Profession": "Software", "Hobbies": "Sleep", "ZodiacSign": "Cancer", "FavoriteGame": "Chess", "FavoriteFood": "Chicken", "Religion": "Muslim" },
    { "FirstName": "Sree Priyanka", "LastName": "Onteru", "DOB": "28 may", "College": "KLU", "Citizenship": "India", "Place": "AP", "City": "Guntur", "MotherName": "Suneetha", "FatherName": "OSR", "Siblings": "No", "Zipcode": "522213", "Linkedin": "https://abc.com", "Contact": "1234567", "Gmail": "abc@gmail.com", "Profession": "Software", "Hobbies": "Sleep", "ZodiacSign": "Cancer", "FavoriteGame": "Chess", "FavoriteFood": "Chicken", "Religion": "Muslim" },
    { "FirstName": "Sree Priyanka", "LastName": "Onteru", "DOB": "21 may", "College": "KLU", "Citizenship": "India", "Place": "AP", "City": "Guntur", "MotherName": "Suneetha", "FatherName": "OSR", "Siblings": "No", "Zipcode": "522213", "Linkedin": "https://abc.com", "Contact": "1234567", "Gmail": "abc@gmail.com", "Profession": "Software", "Hobbies": "Sleep", "ZodiacSign": "Cancer", "FavoriteGame": "Chess", "FavoriteFood": "Chicken", "Religion": "Muslim" },
    { "FirstName": "Sree Priyanka", "LastName": "Onteru", "DOB": "21 may", "College": "KLU", "Citizenship": "India", "Place": "AP", "City": "Guntur", "MotherName": "Suneetha", "FatherName": "OSR", "Siblings": "No", "Zipcode": "522213", "Linkedin": "https://abc.com", "Contact": "1234567", "Gmail": "abc@gmail.com", "Profession": "Software", "Hobbies": "Sleep", "ZodiacSign": "Cancer", "FavoriteGame": "Chess", "FavoriteFood": "Chicken", "Religion": "Muslim" },
    { "FirstName": "Sree Priyanka", "LastName": "Onteru", "DOB": "21 may", "College": "KLU", "Citizenship": "India", "Place": "AP", "City": "Guntur", "MotherName": "Suneetha", "FatherName": "OSR", "Siblings": "No", "Zipcode": "522213", "Linkedin": "https://abc.com", "Contact": "1234567", "Gmail": "abc@gmail.com", "Profession": "Software", "Hobbies": "Sleep", "ZodiacSign": "Cancer", "FavoriteGame": "Chess", "FavoriteFood": "Chicken", "Religion": "Muslim" },
]